{"name": "Random Scenario three", "status": "failed", "statusDetails": {"message": "AttributeError: type object 'Context' has no attribute 'driver'", "trace": "by = 'xpath', web_element = \"//*[text()='Documentation']\"\n\n    @staticmethod\n    def is_page_loaded(by, web_element):\n        \"\"\"\n        This function waits for page to be loaded\n        :param by: method to locate web-element\n        :param web_element: locator\n        :return: boolean value if page is loaded or not\n        \"\"\"\n        try:\n>           element = Context.driver.find_element(by, web_element)\nE           AttributeError: type object 'Context' has no attribute 'driver'\n\n../src/base/base_class.py:336: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\n.0 = <list_iterator object at 0x104f87100>\n\n>   kwargs = {arg: kwargs[arg] if arg in kwargs else request.getfixturevalue(arg) for arg in args}\n\n../venv/lib/python3.9/site-packages/pytest_bdd/scenario.py:154: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../venv/lib/python3.9/site-packages/_pytest/fixtures.py:585: in getfixturevalue\n    fixturedef = self._get_active_fixturedef(argname)\n../venv/lib/python3.9/site-packages/_pytest/fixtures.py:607: in _get_active_fixturedef\n    self._compute_fixture_value(fixturedef)\n../venv/lib/python3.9/site-packages/_pytest/fixtures.py:693: in _compute_fixture_value\n    fixturedef.execute(request=subrequest)\n../venv/lib/python3.9/site-packages/_pytest/fixtures.py:1069: in execute\n    result = ihook.pytest_fixture_setup(fixturedef=self, request=request)\n../venv/lib/python3.9/site-packages/pluggy/_hooks.py:493: in __call__\n    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)\n../venv/lib/python3.9/site-packages/pluggy/_manager.py:115: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n../venv/lib/python3.9/site-packages/_pytest/fixtures.py:1123: in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n../venv/lib/python3.9/site-packages/_pytest/fixtures.py:902: in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n../conftest.py:125: in navigate_to_dashboards_page\n    dashboards_page = DashboardsPage()\n../src/genesis/pages/dashboard.py:9: in __init__\n    BaseClass.is_page_loaded(By.XPATH, self.__documentation_locator)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nby = 'xpath', web_element = \"//*[text()='Documentation']\"\n\n    @staticmethod\n    def is_page_loaded(by, web_element):\n        \"\"\"\n        This function waits for page to be loaded\n        :param by: method to locate web-element\n        :param web_element: locator\n        :return: boolean value if page is loaded or not\n        \"\"\"\n        try:\n            element = Context.driver.find_element(by, web_element)\n            WebDriverWait(Context.driver, 15).until(wait.presence_of_element_located((by, web_element)))\n            presence_of_value = element.is_displayed()\n            logger.info(f'Page load successfully')\n            return presence_of_value\n        except Exception as error:\n            logger.info('exception is hit')\n>           BaseClass.take_screenshot(Context.driver)\nE           AttributeError: type object 'Context' has no attribute 'driver'\n\n../src/base/base_class.py:343: AttributeError"}, "description": "Random Scenario three", "steps": [{"name": "Given I want to do something three", "status": "failed", "statusDetails": {"message": "type object 'Context' has no attribute 'driver'", "trace": "AttributeError: type object 'Context' has no attribute 'driver'\n"}, "start": 1696769722394, "stop": 1696769722397}], "attachments": [{"name": "log", "source": "0957ab05-8cd9-4f0c-8f4f-31a1d75d2cb2-attachment.txt", "type": "text/plain"}], "start": 1696769722394, "stop": 1696769722397, "uuid": "8a1a7a23-eb58-bf18-7479-2fb205993a65", "historyId": "8a1a7a23eb58bf1874792fb205993a65", "fullName": "tests/features/third_feature.feature:Random Scenario three", "labels": [{"name": "host", "value": "GDCMB-104.ultrahub"}, {"name": "thread", "value": "40901-MainThread"}, {"name": "framework", "value": "pytest-bdd"}, {"name": "language", "value": "cpython3"}, {"name": "feature", "value": "Sample feature three"}, {"name": "tag", "value": "usefixtures"}, {"name": "tag", "value": "2108"}], "links": [{"type": "tms", "url": "https://gdcgroup.testrail.io/index.php?/cases/view/2108", "name": "https://gdcgroup.testrail.io/index.php?/cases/view/2108"}]}